### PR TITLE
`getGameDirectory()`

### PR DESCRIPTION
**Pull request by Vladg24YT**
Adds a new method in `MInecraftImpl` that returns the environment's working directory. Also adds a bit of info into the README regarding the usage of RML.

### CODE REVIEW

**Comment by unnaturalistic** [comment]
How is this useful?
All files created by mods already go in the minecraft dir.
They can directly change everything!

**Comment by Vladg24YT** [comment]
Some modders may want to access mod configuration files or store their own files in `.minecraft` (as in JourneyMap or CraftTweaker)

**Comment by unnaturalistic** [comment]
But still, any files they create will *still* be in the default minecraft dir because its defined in a java argument, even if the argument isn't set it would still be in the working directory of the client/server jar

**Review by 5GameMaker — APPROVED** [review]
Will be merging this soon

**Pull request merged**
