### PR TITLE
A simple file manager

### PR DESCRIPTION
**Pull request by unnaturalistic**

### CODE REVIEW

**Comment by 5GameMaker** [comment]
This PR does not follow the project's [Code Style](https://github.com/RosepadMC/Rosepad/blob/master/docs/contributing/code-style.md)

Also, this seems like just a wrapper over some basic Java file management functions. Is there a reason to add this to the codebase?

**Comment by unnaturalistic** [comment]
> This PR does not follow the project's [Code Style](https://github.com/RosepadMC/Rosepad/blob/master/docs/contributing/code-style.md)
> 
> Also, this seems like just a wrapper over some basic Java file management functions. Is there a reason to add this to the codebase?

1, fixin that right up

2, yeah to stop the usage of repeating the simlpe fm functions over and over again in a mod codebase

**Comment by 5GameMaker** [comment]
None of these functions are long to write nor are there no alternatives in the standard library. See https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html

**Comment by unnaturalistic** [comment]
Good point, closin the PR

**Pull request closed without merging**
